export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADDNEWPROJECT_TOLIST ='ADDNEWPROJECT_TOLIST';
export const FORM_VALIDATION ='FORM_VALIDATION';
export const SELECTED_PROJECT ='SELECTED_PROJECT';

