export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADDNEWPROJECT_TOLIST ='ADDNEWPROJECT_TOLIST';
export const FORM_VALIDATION ='FORM_VALIDATION';
export const SELECTED_PROJECT ='SELECTED_PROJECT';
export const DELETE_PROJECT ='DELETE_PROJECT';

export const GET_TASKSBYID ='GET_TASKSBYID';
export const ADDNEWTASK_TOLIST ='ADDNEWTASK_TOLIST';
export const DELETE_TASK ='DELETE_TASK';
export const COMPLETE_TASK ='COMPLETE_TASK';
export const ONGOING_TASK ='ONGOING_TASK';
export const UPDATE_TASK ='UPDATE_TASK';